# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sortdialog.ui'
#
# Created: Tue Apr 30 17:23:12 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SortDialog(object):
    def setupUi(self, SortDialog):
        SortDialog.setObjectName(_fromUtf8("SortDialog"))
        SortDialog.resize(299, 398)
        self.gridlayout = QtGui.QGridLayout(SortDialog)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.okButton = QtGui.QPushButton(SortDialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.vboxlayout.addWidget(self.okButton)
        self.cancelButton = QtGui.QPushButton(SortDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.vboxlayout.addWidget(self.cancelButton)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.moreButton = QtGui.QPushButton(SortDialog)
        self.moreButton.setCheckable(True)
        self.moreButton.setObjectName(_fromUtf8("moreButton"))
        self.vboxlayout.addWidget(self.moreButton)
        self.gridlayout.addLayout(self.vboxlayout, 0, 1, 2, 1)
        self.tertiaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.tertiaryGroupBox.setObjectName(_fromUtf8("tertiaryGroupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.tertiaryGroupBox)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.tertiaryOrderCombo = QtGui.QComboBox(self.tertiaryGroupBox)
        self.tertiaryOrderCombo.setObjectName(_fromUtf8("tertiaryOrderCombo"))
        self.tertiaryOrderCombo.addItem(_fromUtf8(""))
        self.tertiaryOrderCombo.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.tertiaryOrderCombo, 1, 1, 1, 2)
        self.tertiaryOrderLabel = QtGui.QLabel(self.tertiaryGroupBox)
        self.tertiaryOrderLabel.setObjectName(_fromUtf8("tertiaryOrderLabel"))
        self.gridlayout1.addWidget(self.tertiaryOrderLabel, 1, 0, 1, 1)
        self.tertiaryColumnLabel = QtGui.QLabel(self.tertiaryGroupBox)
        self.tertiaryColumnLabel.setObjectName(_fromUtf8("tertiaryColumnLabel"))
        self.gridlayout1.addWidget(self.tertiaryColumnLabel, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1, 0, 2, 1, 1)
        self.tertiaryColumnCombo = QtGui.QComboBox(self.tertiaryGroupBox)
        self.tertiaryColumnCombo.setObjectName(_fromUtf8("tertiaryColumnCombo"))
        self.tertiaryColumnCombo.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.tertiaryColumnCombo, 0, 1, 1, 1)
        self.gridlayout.addWidget(self.tertiaryGroupBox, 3, 0, 1, 1)
        self.secondaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.secondaryGroupBox.setObjectName(_fromUtf8("secondaryGroupBox"))
        self.gridlayout2 = QtGui.QGridLayout(self.secondaryGroupBox)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.secondaryOrderCombo = QtGui.QComboBox(self.secondaryGroupBox)
        self.secondaryOrderCombo.setObjectName(_fromUtf8("secondaryOrderCombo"))
        self.secondaryOrderCombo.addItem(_fromUtf8(""))
        self.secondaryOrderCombo.addItem(_fromUtf8(""))
        self.gridlayout2.addWidget(self.secondaryOrderCombo, 1, 1, 1, 2)
        self.secondaryOrderLabel = QtGui.QLabel(self.secondaryGroupBox)
        self.secondaryOrderLabel.setObjectName(_fromUtf8("secondaryOrderLabel"))
        self.gridlayout2.addWidget(self.secondaryOrderLabel, 1, 0, 1, 1)
        self.secondaryColumnLabel = QtGui.QLabel(self.secondaryGroupBox)
        self.secondaryColumnLabel.setObjectName(_fromUtf8("secondaryColumnLabel"))
        self.gridlayout2.addWidget(self.secondaryColumnLabel, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem2, 0, 2, 1, 1)
        self.secondaryColumnCombo = QtGui.QComboBox(self.secondaryGroupBox)
        self.secondaryColumnCombo.setObjectName(_fromUtf8("secondaryColumnCombo"))
        self.secondaryColumnCombo.addItem(_fromUtf8(""))
        self.gridlayout2.addWidget(self.secondaryColumnCombo, 0, 1, 1, 1)
        self.gridlayout.addWidget(self.secondaryGroupBox, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.primaryGroupBox = QtGui.QGroupBox(SortDialog)
        self.primaryGroupBox.setObjectName(_fromUtf8("primaryGroupBox"))
        self.gridlayout3 = QtGui.QGridLayout(self.primaryGroupBox)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.primaryOrderCombo = QtGui.QComboBox(self.primaryGroupBox)
        self.primaryOrderCombo.setObjectName(_fromUtf8("primaryOrderCombo"))
        self.primaryOrderCombo.addItem(_fromUtf8(""))
        self.primaryOrderCombo.addItem(_fromUtf8(""))
        self.gridlayout3.addWidget(self.primaryOrderCombo, 1, 1, 1, 2)
        self.primaryOrderLabel = QtGui.QLabel(self.primaryGroupBox)
        self.primaryOrderLabel.setObjectName(_fromUtf8("primaryOrderLabel"))
        self.gridlayout3.addWidget(self.primaryOrderLabel, 1, 0, 1, 1)
        self.primaryColumnLabel = QtGui.QLabel(self.primaryGroupBox)
        self.primaryColumnLabel.setObjectName(_fromUtf8("primaryColumnLabel"))
        self.gridlayout3.addWidget(self.primaryColumnLabel, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout3.addItem(spacerItem4, 0, 2, 1, 1)
        self.primaryColumnCombo = QtGui.QComboBox(self.primaryGroupBox)
        self.primaryColumnCombo.setObjectName(_fromUtf8("primaryColumnCombo"))
        self.primaryColumnCombo.addItem(_fromUtf8(""))
        self.gridlayout3.addWidget(self.primaryColumnCombo, 0, 1, 1, 1)
        self.gridlayout.addWidget(self.primaryGroupBox, 0, 0, 1, 1)

        self.retranslateUi(SortDialog)
        QtCore.QObject.connect(self.moreButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.secondaryGroupBox.setVisible)
        QtCore.QObject.connect(self.moreButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.tertiaryGroupBox.setVisible)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SortDialog.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SortDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SortDialog)
        SortDialog.setTabOrder(self.primaryColumnCombo, self.primaryOrderCombo)
        SortDialog.setTabOrder(self.primaryOrderCombo, self.secondaryColumnCombo)
        SortDialog.setTabOrder(self.secondaryColumnCombo, self.secondaryOrderCombo)
        SortDialog.setTabOrder(self.secondaryOrderCombo, self.tertiaryColumnCombo)
        SortDialog.setTabOrder(self.tertiaryColumnCombo, self.tertiaryOrderCombo)
        SortDialog.setTabOrder(self.tertiaryOrderCombo, self.okButton)
        SortDialog.setTabOrder(self.okButton, self.cancelButton)
        SortDialog.setTabOrder(self.cancelButton, self.moreButton)

    def retranslateUi(self, SortDialog):
        SortDialog.setWindowTitle(QtGui.QApplication.translate("SortDialog", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("SortDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("SortDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.moreButton.setText(QtGui.QApplication.translate("SortDialog", "&More", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Tertiary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryOrderLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Order:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryColumnLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Column:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tertiaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Secondary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryOrderLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Order:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryColumnLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Column:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryGroupBox.setTitle(QtGui.QApplication.translate("SortDialog", "&Primary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryOrderCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryOrderCombo.setItemText(1, QtGui.QApplication.translate("SortDialog", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryOrderLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Order:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryColumnLabel.setText(QtGui.QApplication.translate("SortDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Column:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryColumnCombo.setItemText(0, QtGui.QApplication.translate("SortDialog", "None", None, QtGui.QApplication.UnicodeUTF8))

